buttonsDict = {
    "0" : '//*[@id="sciout"]/tbody/tr[2]/td[2]/div/div[4]/span[1]',
    "1" : '//*[@id="sciout"]/tbody/tr[2]/td[2]/div/div[3]/span[1]',
    "2" : '//*[@id="sciout"]/tbody/tr[2]/td[2]/div/div[3]/span[2]',
    "3" : '//*[@id="sciout"]/tbody/tr[2]/td[2]/div/div[3]/span[3]',
    "4" : '//*[@id="sciout"]/tbody/tr[2]/td[2]/div/div[2]/span[1]',
    "5" : '//*[@id="sciout"]/tbody/tr[2]/td[2]/div/div[2]/span[2]',
    "6" : '//*[@id="sciout"]/tbody/tr[2]/td[2]/div/div[2]/span[3]',
    "7" : '//*[@id="sciout"]/tbody/tr[2]/td[2]/div/div[1]/span[1]',
    "8" : '//*[@id="sciout"]/tbody/tr[2]/td[2]/div/div[1]/span[2]',
    "9" : '//*[@id="sciout"]/tbody/tr[2]/td[2]/div/div[1]/span[3]',
    '-' : '//*[@id="sciout"]/tbody/tr[2]/td[2]/div/div[2]/span[4]',
    '.' : '//*[@id="sciout"]/tbody/tr[2]/td[2]/div/div[4]/span[2]',
    "add" : '//*[@id="sciout"]/tbody/tr[2]/td[2]/div/div[1]/span[4]',
    "substract" : '//*[@id="sciout"]/tbody/tr[2]/td[2]/div/div[2]/span[4]',
    "division" : '//*[@id="sciout"]/tbody/tr[2]/td[2]/div/div[4]/span[4]',
    "multipication" : '//*[@id="sciout"]/tbody/tr[2]/td[2]/div/div[3]/span[4]',
    "sin" : '//*[@id="sciout"]/tbody/tr[2]/td[1]/div/div[1]/span[1]',
    "asin": '//*[@id="sciout"]/tbody/tr[2]/td[1]/div/div[2]/span[1]',
    "cos" : '//*[@id="sciout"]/tbody/tr[2]/td[1]/div/div[1]/span[2]',
    "acos" : '//*[@id="sciout"]/tbody/tr[2]/td[1]/div/div[2]/span[2]',
    "tan" : '//*[@id="sciout"]/tbody/tr[2]/td[1]/div/div[1]/span[3]',
    "atan" : '//*[@id="sciout"]/tbody/tr[2]/td[1]/div/div[2]/span[3]',
    "degree" : '//*[@id="scirdsettingd"]',
    "radian" : '//*[@id="scirdsettingr"]',
    "log" : '//*[@id="sciout"]/tbody/tr[2]/td[1]/div/div[4]/span[5]',
    "ln" : '//*[@id="sciout"]/tbody/tr[2]/td[1]/div/div[4]/span[4]',
    "factorial" : '//*[@id="sciout"]/tbody/tr[2]/td[1]/div/div[5]/span[5]',
    "10exp": '//*[@id="sciout"]/tbody/tr[2]/td[1]/div/div[3]/span[5]',
    "expotent": '//*[@id="sciout"]/tbody/tr[2]/td[1]/div/div[3]/span[4]',
    "xSquared" : '/html/body/div[3]/div/table/tbody/tr/td[1]/table/tbody/tr[2]/td[1]/div/div[3]/span[3]',
    "xCubed" : '//*[@id="sciout"]/tbody/tr[2]/td[1]/div/div[3]/span[2]',
    "xPowY" : '//*[@id="sciout"]/tbody/tr[2]/td[1]/div/div[3]/span[1]',
    "squaredRoot": '/html/body/div[3]/div/table/tbody/tr/td[1]/table/tbody/tr[2]/td[1]/div/div[4]/span[3]',
    "cubeRoot" : '/html/body/div[3]/div/table/tbody/tr/td[1]/table/tbody/tr[2]/td[1]/div/div[4]/span[2]',
    "yRootX" : '/html/body/div[3]/div/table/tbody/tr/td[1]/table/tbody/tr[2]/td[1]/div/div[4]/span[1]',
    "clear": '//*[@id="sciout"]/tbody/tr[2]/td[2]/div/div[5]/span[3]',
    "equals" : '//*[@id="sciout"]/tbody/tr[2]/td[2]/div/div[5]/span[4]',
    "leftBracket" : '/html/body/div[3]/div/table/tbody/tr/td[1]/table/tbody/tr[2]/td[1]/div/div[5]/span[1]',
    "rightBracket" : '/html/body/div[3]/div/table/tbody/tr/td[1]/table/tbody/tr[2]/td[1]/div/div[5]/span[2]' 

}


